---
- name: Ensure namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ argocd_namespace }}"
    state: present
    kubeconfig: ".kube/config"

- name: Add Argo Helm repo
  kubernetes.core.helm_repository:
    name: argo
    repo_url: "{{ argocd_helm_repo }}"
    kubeconfig: .kube/config

- name: Copy values file to node
  ansible.builtin.template:
    src: "templates/argocd-values.yml.j2"
    dest: "/tmp/argocd-values.yml"

- name: Deploy Argo CD via Helm
  kubernetes.core.helm:
    name: "{{ argocd_release_name }}"
    chart_ref: "argo/argo-cd"
    chart_version: "{{ argocd_chart_version }}"
    release_namespace: "{{ argocd_namespace }}"
    create_namespace: false
    values_files:
      - /tmp/argocd-values.yml
    wait: true
    update_repo_cache: true
    kubeconfig: ".kube/config"