mgmt:
  hosts:
    srv-001.devops.ls.eee.intern:

k3s_cluster:
  children:
    loadbalancer:
      hosts:
        srv-001.devops.ls.eee.intern:
    server:
      hosts:
        srv-019.devops.ls.eee.intern:
        srv-022.devops.ls.eee.intern:
        srv-023.devops.ls.eee.intern:
    agent:
      hosts: {}
      