---
# PRODUCTION INVENTORY
all:
  hosts:
    srv-001.devops.ls.eee.intern:
      ansible_connection: local
      ansible_user: ansible

    srv-019.devops.ls.eee.intern:
      ansible_host: srv-019.devops.ls.eee.intern
      ansible_user: ansible
      ansible_ssh_private_key_file: /home/ansible/.ssh/ansible@srv-019

    srv-022.devops.ls.eee.intern:
      ansible_host: srv-022.devops.ls.eee.intern
      ansible_user: ansible
      ansible_ssh_private_key_file: /home/ansible/.ssh/ansible@srv-022

    srv-023.devops.ls.eee.intern:
      ansible_host: srv-023.devops.ls.eee.intern
      ansible_user: ansible
      ansible_ssh_private_key_file: /home/ansible/.ssh/ansible@srv-023


