---
# PRODUCTION INVENTORY
all: 
  vars:
    ansible_user: labadmin
    ansible_become_pass: CHANGE_ME
    ansible_ssh_private_key_file: /home/labadmin/.ssh/id_jump

mgmt:
  hosts:
    srv-001.devops.ls.eee.intern:

lb:
  hosts:
    srv-001.devops.ls.eee.intern:

k3s_cluster:
  children:
    server:
      hosts:
        srv-019.devops.ls.eee.intern:
        srv-022.devops.ls.eee.intern:
        srv-023.devops.ls.eee.intern:
    agent:
      hosts:
