---
# versions
helm_version: "v3.15.4"
kubectl_version: "v1.31.0"
python_kubernetes_version: "34.1.0"
argocd_chart_version: "8.6.3"

# kubeconfig
kubeconfig_user: "{{ ansible_user }}"
kubeconfig_src_node: "{{ groups['server'][0] }}"
kubeconfig_api_endpoint: "{{ groups['loadbalancer'][0] }}"

# venv for ansible helm
k3s_ansible_venv_path: "/home/{{ ansible_user }}/.venv"

# os type for kube_tool installments
os_arch: "amd64"
os_type: "linux"
