name: Test Web
on:
  workflow_call:

jobs:
  test-unit:
    name: Test (Unit)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache-node_modules.outputs.cache-hit != true
        run: pnpm install --frozen-lockfile

      - name: Test (Unit)
        run: pnpm run test:unit

  test-e2e:
    name: Test (E2E)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    env:
      NODE_ENV: ci
      API_BASE_URL: ${{ vars.CI_API_BASE_URL }}
      ACCESS_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      # speed up for playwright install
      - name: Uninstall man
        run: sudo apt-get --yes remove --purge man-db

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache-node_modules.outputs.cache-hit != true
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Run Playwright Tests
        run: pnpm run test:e2e
